### ISSUE TITLE
Ability to list more than one verified accounts

### ISSUE THREAD

**Issue by mwclemy** [mxenabled/processor-tokens-client-quickstart#26]
I verified more than one accounts associated with my user but I was only able to see one verified account at a time in the list.

**Comment by codingLogan** [comment]
@mwclemy I'd be happy to look into this issue.

**Comment by codingLogan** [comment]
Diving in deeper, this QuickStart app already supports listing multiple verified accounts, if multiple accounts are returned from the API.  Currently the API is returning a single account, so only one is rendered.

I'll mark this as closed, since this QuickStart is functionally working as expected.  If others see this issue and it's reported again we can keep an issue open until it's resolved internally.

**Comment by mwclemy** [comment]
Thanks for looking into this.
